### ISSUE TITLE
Reproducible crash on save (when removing objets that were removed from FBX files)

### ISSUE THREAD

**Issue by martin-t** [rg3dengine/rusty-editor#63]
Steps to repro:
- Load https://github.com/rustcycles/rustcycles/blob/master/data/arena/arena.rgs
- Delete Poles (3:1)
- Save Scene

How this happened:
The arena.fbx (not rgs) model used to have a Poles object in it but i deleted it. The Poles object (with a collider) is still present in rusty-editor's scene graph so i wanted to remove it there too.

Backtrace:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `3`,
 right: `4`', /home/martin/dev/rust/rg3d/rg3d-physics/build/rg3d-physics3d/../../src/collider.rs:45:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/panicking.rs:107:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/panicking.rs:145:5
   4: rg3d_physics3d::collider::ColliderContainer::from_raw_parts
             at /home/martin/dev/rust/rg3d/rg3d-physics/build/rg3d-physics3d/../../src/collider.rs:45:9
   5: rg3d::scene::physics::Physics::resolve
             at /home/martin/dev/rust/rg3d/src/scene/physics.rs:608:13
   6: rg3d::scene::physics::Physics::deep_copy
             at /home/martin/dev/rust/rg3d/src/scene/physics.rs:152:9
   7: rg3d::scene::Scene::clone
             at /home/martin/dev/rust/rg3d/src/scene/mod.rs:636:23
   8: rusty_editor::scene::EditorScene::save
             at /home/martin/dev/rust/rusty-editor/src/scene/mod.rs:77:48
   9: rusty_editor::Editor::update
             at /home/martin/dev/rust/rusty-editor/src/main.rs:1705:31
  10: rusty_editor::update
             at /home/martin/dev/rust/rusty-editor/src/main.rs:2046:9
  11: rusty_editor::main::{{closure}}
             at /home/martin/dev/rust/rusty-editor/src/main.rs:2095:13
  12: winit::platform_impl::platform::sticky_exit_callback
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/mod.rs:746:5
  13: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/x11/mod.rs:290:17
  14: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/x11/mod.rs:385:9
  15: winit::platform_impl::platform::EventLoop<T>::run
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/mod.rs:662:56
  16: winit::event_loop::EventLoop<T>::run
             at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/event_loop.rs:154:9
  17: rusty_editor::main
             at /home/martin/dev/rust/rusty-editor/src/main.rs:2093:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mrDIMAS** [comment]
Fixed in https://github.com/rg3dengine/rg3d/commit/8f689ef09753f6c848ddc9c225aa6601c96c1051 and https://github.com/rg3dengine/rusty-editor/commit/2ff302b128abe5bfbf533cc69040e3ab1919c77d
